export const REQUEST_FAIL = 'REQUEST_FAIL';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_LOADING = 'REQUEST_LOADING';
export const ARTICLES = 'ARTICLES';
export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const LOAD_MORE_ARTICLES = 'LOAD_MORE_ARTICLES';